title: Richard's World! 
#description: > # this means to ignore newlines until "baseurl:"
#permalink: ':title/'
domain: https://van-richard.github.io
url: https://van-richard.github.io # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ''


# Author Settings
author: Richard Van # add your name
author-img: test.jpg  # add your photo
about-author: I hate html already. # add description
social-google: citations?user=d0ffBOYAAAAJ&hl=en&oi=sra
social-twitter: OMGITSvanADIUM # add your Twitter handle
social-github: van-richard # add your Github handle
social-linkedin: van-richard # add your Linkedin handle
social-email: van@ou.edu # add your Email address

# Build Settings
markdown: kramdown
kramdown:
  # use Github Flavored Markdown
  input: GFM

plugins:
  - jekyll-sitemap
  # - jekyll-paginate
  - jekyll-paginate-v2
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock

gems:
  - jekyll-paginate-v2

# Due to us using the categories for posts then it is advisable to explicitly specify a 
# permalink structure for the site. Otherwise Jekyll attempts to organize the pages in folders
# by the category names and it doesn't understand multi-categories to well :/
permalink: /:year/:month/:title.html
#permalink: pretty

# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# paginate-multiple:
#   - paginate: 8
#     paginate_path: "./tutorials/bash/page:num/"
#     sub_dir: "/bash"
#   - paginate: 8 
#     paginate_path: ".tutorials/git/page:num/"
#     sub_dir: "/git"

excerpt_separator: "" 
