title: adVANtures 
#description: > # this means to ignore newlines until "baseurl:"
#permalink: ':title/'
domain: https://van-richard.github.io
url: https://van-richard.github.io # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ''

# Author Settings
author: Richard Van 
author-img: test.jpg  
about-author: Computational Biochemistry

# Build Settings
markdown: kramdown
kramdown:
  # use Github Flavored Markdown
  input: GFM

plugins:
  - jekyll-sitemap
  - jemoji

#paginate: 8
# paginate_path: "/:num"

excerpt_separator: "" 
